//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 12:58:05 PM EST 
//


package EventExpenseType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetTableEntryLookupInfoReply complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetTableEntryLookupInfoReply">
 *   &lt;complexContent>
 *     &lt;extension base="{blackbaud_appfx_server_bizops}BizOpsReply">
 *       &lt;sequence>
 *         &lt;element name="CurrentUserCanAdd" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CurrentUserCanUpdate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CurrentUserCanDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Entries" type="{blackbaud_appfx_server_bizops}GetTableEntryListReply" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetTableEntryLookupInfoReply", propOrder = {
    "currentUserCanAdd",
    "currentUserCanUpdate",
    "currentUserCanDelete",
    "description",
    "entries"
})
public class GetTableEntryLookupInfoReply
    extends BizOpsReply
{

    @XmlElement(name = "CurrentUserCanAdd")
    protected boolean currentUserCanAdd;
    @XmlElement(name = "CurrentUserCanUpdate")
    protected boolean currentUserCanUpdate;
    @XmlElement(name = "CurrentUserCanDelete")
    protected boolean currentUserCanDelete;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Entries")
    protected GetTableEntryListReply entries;

    /**
     * Gets the value of the currentUserCanAdd property.
     * 
     */
    public boolean isCurrentUserCanAdd() {
        return currentUserCanAdd;
    }

    /**
     * Sets the value of the currentUserCanAdd property.
     * 
     */
    public void setCurrentUserCanAdd(boolean value) {
        this.currentUserCanAdd = value;
    }

    /**
     * Gets the value of the currentUserCanUpdate property.
     * 
     */
    public boolean isCurrentUserCanUpdate() {
        return currentUserCanUpdate;
    }

    /**
     * Sets the value of the currentUserCanUpdate property.
     * 
     */
    public void setCurrentUserCanUpdate(boolean value) {
        this.currentUserCanUpdate = value;
    }

    /**
     * Gets the value of the currentUserCanDelete property.
     * 
     */
    public boolean isCurrentUserCanDelete() {
        return currentUserCanDelete;
    }

    /**
     * Sets the value of the currentUserCanDelete property.
     * 
     */
    public void setCurrentUserCanDelete(boolean value) {
        this.currentUserCanDelete = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the entries property.
     * 
     * @return
     *     possible object is
     *     {@link GetTableEntryListReply }
     *     
     */
    public GetTableEntryListReply getEntries() {
        return entries;
    }

    /**
     * Sets the value of the entries property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetTableEntryListReply }
     *     
     */
    public void setEntries(GetTableEntryListReply value) {
        this.entries = value;
    }

}
