//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 12:58:05 PM EST 
//


package EventExpenseType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetTableEntryListReply complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetTableEntryListReply">
 *   &lt;complexContent>
 *     &lt;extension base="{blackbaud_appfx_server_bizops}BizOpsReply">
 *       &lt;sequence>
 *         &lt;element name="Rows" type="{blackbaud_appfx_server_bizops}ArrayOfTableEntryListRow" minOccurs="0"/>
 *         &lt;element name="UserDefinedSort" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetTableEntryListReply", propOrder = {
    "rows",
    "userDefinedSort"
})
@XmlRootElement(name = "GetTableEntryListReply")
public class GetTableEntryListReply
    extends BizOpsReply
{

    @XmlElement(name = "Rows")
    protected ArrayOfTableEntryListRow rows;
    @XmlElement(name = "UserDefinedSort", defaultValue = "false")
    protected Boolean userDefinedSort;

    /**
     * Gets the value of the rows property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTableEntryListRow }
     *     
     */
    public ArrayOfTableEntryListRow getRows() {
        return rows;
    }

    /**
     * Sets the value of the rows property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTableEntryListRow }
     *     
     */
    public void setRows(ArrayOfTableEntryListRow value) {
        this.rows = value;
    }

    /**
     * Gets the value of the userDefinedSort property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUserDefinedSort() {
        return userDefinedSort;
    }

    /**
     * Sets the value of the userDefinedSort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserDefinedSort(Boolean value) {
        this.userDefinedSort = value;
    }

}
