//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 12:58:05 PM EST 
//


package EventExpenseType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetTableEntryListRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetTableEntryListRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{blackbaud_appfx_server_bizops}BizOpsRequest">
 *       &lt;sequence>
 *         &lt;element name="IncludeInactive" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="RefreshCache" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetTableEntryListRequest", propOrder = {
    "includeInactive",
    "refreshCache"
})
@XmlRootElement(name = "GetTableEntryListRequest")
public class GetTableEntryListRequest
    extends BizOpsRequest
{

    @XmlElement(name = "IncludeInactive")
    protected boolean includeInactive;
    @XmlElement(name = "RefreshCache")
    protected boolean refreshCache;

    /**
     * Gets the value of the includeInactive property.
     * 
     */
    public boolean isIncludeInactive() {
        return includeInactive;
    }

    /**
     * Sets the value of the includeInactive property.
     * 
     */
    public void setIncludeInactive(boolean value) {
        this.includeInactive = value;
    }

    /**
     * Gets the value of the refreshCache property.
     * 
     */
    public boolean isRefreshCache() {
        return refreshCache;
    }

    /**
     * Sets the value of the refreshCache property.
     * 
     */
    public void setRefreshCache(boolean value) {
        this.refreshCache = value;
    }

}
