//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 12:58:05 PM EST 
//


package EventExpenseType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetTableEntryDataRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetTableEntryDataRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{blackbaud_appfx_server_bizops}BizOpsRequest">
 *       &lt;sequence>
 *         &lt;element name="TableEntryID" type="{http://microsoft.com/wsdl/types/}guid"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetTableEntryDataRequest", propOrder = {
    "tableEntryID"
})
public class GetTableEntryDataRequest
    extends BizOpsRequest
{

    @XmlElement(name = "TableEntryID", required = true)
    protected String tableEntryID;

    /**
     * Gets the value of the tableEntryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableEntryID() {
        return tableEntryID;
    }

    /**
     * Sets the value of the tableEntryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableEntryID(String value) {
        this.tableEntryID = value;
    }

}
