//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 12:58:05 PM EST 
//


package EventExpenseType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GetTableEntryListReply" type="{blackbaud_appfx_server_bizops}GetTableEntryListReply" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getTableEntryListReply"
})
@XmlRootElement(name = "GetTableEntryListEzReply")
public class GetTableEntryListEzReply {

    @XmlElement(name = "GetTableEntryListReply")
    protected GetTableEntryListReply getTableEntryListReply;

    /**
     * Gets the value of the getTableEntryListReply property.
     * 
     * @return
     *     possible object is
     *     {@link GetTableEntryListReply }
     *     
     */
    public GetTableEntryListReply getGetTableEntryListReply() {
        return getTableEntryListReply;
    }

    /**
     * Sets the value of the getTableEntryListReply property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetTableEntryListReply }
     *     
     */
    public void setGetTableEntryListReply(GetTableEntryListReply value) {
        this.getTableEntryListReply = value;
    }

}
