//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 12:58:05 PM EST 
//


package EventExpenseType;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the EventExpenseType package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetTableEntryLookupInfoRequest_QNAME = new QName("blackbaud_appfx_server_bizops", "GetTableEntryLookupInfoRequest");
    private final static QName _UpdateTableEntryRequest_QNAME = new QName("blackbaud_appfx_server_bizops", "UpdateTableEntryRequest");
    private final static QName _GetTableEntryDescriptionReply_QNAME = new QName("blackbaud_appfx_server_bizops", "GetTableEntryDescriptionReply");
    private final static QName _GetTableEntryDataRequest_QNAME = new QName("blackbaud_appfx_server_bizops", "GetTableEntryDataRequest");
    private final static QName _GetTableEntryListReply_QNAME = new QName("blackbaud_appfx_server_bizops", "GetTableEntryListReply");
    private final static QName _GetTableEntryDescriptionRequest_QNAME = new QName("blackbaud_appfx_server_bizops", "GetTableEntryDescriptionRequest");
    private final static QName _AddTableEntryReply_QNAME = new QName("blackbaud_appfx_server_bizops", "AddTableEntryReply");
    private final static QName _GetTableEntryLookupInfoReply_QNAME = new QName("blackbaud_appfx_server_bizops", "GetTableEntryLookupInfoReply");
    private final static QName _UpdateTableEntryReply_QNAME = new QName("blackbaud_appfx_server_bizops", "UpdateTableEntryReply");
    private final static QName _GetTableEntryIDReply_QNAME = new QName("blackbaud_appfx_server_bizops", "GetTableEntryIDReply");
    private final static QName _AddTableEntryRequest_QNAME = new QName("blackbaud_appfx_server_bizops", "AddTableEntryRequest");
    private final static QName _GetTableEntryIDRequest_QNAME = new QName("blackbaud_appfx_server_bizops", "GetTableEntryIDRequest");
    private final static QName _GetTableEntryListRequest_QNAME = new QName("blackbaud_appfx_server_bizops", "GetTableEntryListRequest");
    private final static QName _DeleteTableEntryRequest_QNAME = new QName("blackbaud_appfx_server_bizops", "DeleteTableEntryRequest");
    private final static QName _GetTableEntryDataReply_QNAME = new QName("blackbaud_appfx_server_bizops", "GetTableEntryDataReply");
    private final static QName _DeleteTableEntryReply_QNAME = new QName("blackbaud_appfx_server_bizops", "DeleteTableEntryReply");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: EventExpenseType
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTableEntryDescriptionEzReply }
     * 
     */
    public GetTableEntryDescriptionEzReply createGetTableEntryDescriptionEzReply() {
        return new GetTableEntryDescriptionEzReply();
    }

    /**
     * Create an instance of {@link GetTableEntryIDRequest }
     * 
     */
    public GetTableEntryIDRequest createGetTableEntryIDRequest() {
        return new GetTableEntryIDRequest();
    }

    /**
     * Create an instance of {@link GetTableEntryListRequest }
     * 
     */
    public GetTableEntryListRequest createGetTableEntryListRequest() {
        return new GetTableEntryListRequest();
    }

    /**
     * Create an instance of {@link AddTableEntryReply }
     * 
     */
    public AddTableEntryReply createAddTableEntryReply() {
        return new AddTableEntryReply();
    }

    /**
     * Create an instance of {@link BizOpsErrorDetail }
     * 
     */
    public BizOpsErrorDetail createBizOpsErrorDetail() {
        return new BizOpsErrorDetail();
    }

    /**
     * Create an instance of {@link SessionStartRequest }
     * 
     */
    public SessionStartRequest createSessionStartRequest() {
        return new SessionStartRequest();
    }

    /**
     * Create an instance of {@link DeleteTableEntryRequest }
     * 
     */
    public DeleteTableEntryRequest createDeleteTableEntryRequest() {
        return new DeleteTableEntryRequest();
    }

    /**
     * Create an instance of {@link GetTableEntryIDEzRequest }
     * 
     */
    public GetTableEntryIDEzRequest createGetTableEntryIDEzRequest() {
        return new GetTableEntryIDEzRequest();
    }

    /**
     * Create an instance of {@link PingRequest }
     * 
     */
    public PingRequest createPingRequest() {
        return new PingRequest();
    }

    /**
     * Create an instance of {@link BizOpsSessionStartReply }
     * 
     */
    public BizOpsSessionStartReply createBizOpsSessionStartReply() {
        return new BizOpsSessionStartReply();
    }

    /**
     * Create an instance of {@link SessionStartReply }
     * 
     */
    public SessionStartReply createSessionStartReply() {
        return new SessionStartReply();
    }

    /**
     * Create an instance of {@link PingReply }
     * 
     */
    public PingReply createPingReply() {
        return new PingReply();
    }

    /**
     * Create an instance of {@link UpdateTableEntryRequest }
     * 
     */
    public UpdateTableEntryRequest createUpdateTableEntryRequest() {
        return new UpdateTableEntryRequest();
    }

    /**
     * Create an instance of {@link GetTableEntryListEzRequest }
     * 
     */
    public GetTableEntryListEzRequest createGetTableEntryListEzRequest() {
        return new GetTableEntryListEzRequest();
    }

    /**
     * Create an instance of {@link GetTableEntryLookupInfoRequest }
     * 
     */
    public GetTableEntryLookupInfoRequest createGetTableEntryLookupInfoRequest() {
        return new GetTableEntryLookupInfoRequest();
    }

    /**
     * Create an instance of {@link GetTableEntryIDEzEzReply }
     * 
     */
    public GetTableEntryIDEzEzReply createGetTableEntryIDEzEzReply() {
        return new GetTableEntryIDEzEzReply();
    }

    /**
     * Create an instance of {@link GetTableEntryDescriptionEzRequest }
     * 
     */
    public GetTableEntryDescriptionEzRequest createGetTableEntryDescriptionEzRequest() {
        return new GetTableEntryDescriptionEzRequest();
    }

    /**
     * Create an instance of {@link GetTableEntryDescriptionReply }
     * 
     */
    public GetTableEntryDescriptionReply createGetTableEntryDescriptionReply() {
        return new GetTableEntryDescriptionReply();
    }

    /**
     * Create an instance of {@link GetTableEntryListEzReply }
     * 
     */
    public GetTableEntryListEzReply createGetTableEntryListEzReply() {
        return new GetTableEntryListEzReply();
    }

    /**
     * Create an instance of {@link ArrayOfTableEntryListRow }
     * 
     */
    public ArrayOfTableEntryListRow createArrayOfTableEntryListRow() {
        return new ArrayOfTableEntryListRow();
    }

    /**
     * Create an instance of {@link GetTableEntryDataRequest }
     * 
     */
    public GetTableEntryDataRequest createGetTableEntryDataRequest() {
        return new GetTableEntryDataRequest();
    }

    /**
     * Create an instance of {@link AddTableEntryRequest }
     * 
     */
    public AddTableEntryRequest createAddTableEntryRequest() {
        return new AddTableEntryRequest();
    }

    /**
     * Create an instance of {@link TableEntryListRow }
     * 
     */
    public TableEntryListRow createTableEntryListRow() {
        return new TableEntryListRow();
    }

    /**
     * Create an instance of {@link UpdateTableEntryReply }
     * 
     */
    public UpdateTableEntryReply createUpdateTableEntryReply() {
        return new UpdateTableEntryReply();
    }

    /**
     * Create an instance of {@link GetTableEntryDataReply }
     * 
     */
    public GetTableEntryDataReply createGetTableEntryDataReply() {
        return new GetTableEntryDataReply();
    }

    /**
     * Create an instance of {@link GetTableEntryDescriptionRequest }
     * 
     */
    public GetTableEntryDescriptionRequest createGetTableEntryDescriptionRequest() {
        return new GetTableEntryDescriptionRequest();
    }

    /**
     * Create an instance of {@link GetTableEntryLookupInfoReply }
     * 
     */
    public GetTableEntryLookupInfoReply createGetTableEntryLookupInfoReply() {
        return new GetTableEntryLookupInfoReply();
    }

    /**
     * Create an instance of {@link GetTableEntryIDReply }
     * 
     */
    public GetTableEntryIDReply createGetTableEntryIDReply() {
        return new GetTableEntryIDReply();
    }

    /**
     * Create an instance of {@link GetTableEntryListReply }
     * 
     */
    public GetTableEntryListReply createGetTableEntryListReply() {
        return new GetTableEntryListReply();
    }

    /**
     * Create an instance of {@link DeleteTableEntryReply }
     * 
     */
    public DeleteTableEntryReply createDeleteTableEntryReply() {
        return new DeleteTableEntryReply();
    }

    /**
     * Create an instance of {@link SessionEndRequest }
     * 
     */
    public SessionEndRequest createSessionEndRequest() {
        return new SessionEndRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTableEntryLookupInfoRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "GetTableEntryLookupInfoRequest")
    public JAXBElement<GetTableEntryLookupInfoRequest> createGetTableEntryLookupInfoRequest(GetTableEntryLookupInfoRequest value) {
        return new JAXBElement<GetTableEntryLookupInfoRequest>(_GetTableEntryLookupInfoRequest_QNAME, GetTableEntryLookupInfoRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateTableEntryRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "UpdateTableEntryRequest")
    public JAXBElement<UpdateTableEntryRequest> createUpdateTableEntryRequest(UpdateTableEntryRequest value) {
        return new JAXBElement<UpdateTableEntryRequest>(_UpdateTableEntryRequest_QNAME, UpdateTableEntryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTableEntryDescriptionReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "GetTableEntryDescriptionReply")
    public JAXBElement<GetTableEntryDescriptionReply> createGetTableEntryDescriptionReply(GetTableEntryDescriptionReply value) {
        return new JAXBElement<GetTableEntryDescriptionReply>(_GetTableEntryDescriptionReply_QNAME, GetTableEntryDescriptionReply.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTableEntryDataRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "GetTableEntryDataRequest")
    public JAXBElement<GetTableEntryDataRequest> createGetTableEntryDataRequest(GetTableEntryDataRequest value) {
        return new JAXBElement<GetTableEntryDataRequest>(_GetTableEntryDataRequest_QNAME, GetTableEntryDataRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTableEntryListReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "GetTableEntryListReply")
    public JAXBElement<GetTableEntryListReply> createGetTableEntryListReply(GetTableEntryListReply value) {
        return new JAXBElement<GetTableEntryListReply>(_GetTableEntryListReply_QNAME, GetTableEntryListReply.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTableEntryDescriptionRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "GetTableEntryDescriptionRequest")
    public JAXBElement<GetTableEntryDescriptionRequest> createGetTableEntryDescriptionRequest(GetTableEntryDescriptionRequest value) {
        return new JAXBElement<GetTableEntryDescriptionRequest>(_GetTableEntryDescriptionRequest_QNAME, GetTableEntryDescriptionRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddTableEntryReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "AddTableEntryReply")
    public JAXBElement<AddTableEntryReply> createAddTableEntryReply(AddTableEntryReply value) {
        return new JAXBElement<AddTableEntryReply>(_AddTableEntryReply_QNAME, AddTableEntryReply.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTableEntryLookupInfoReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "GetTableEntryLookupInfoReply")
    public JAXBElement<GetTableEntryLookupInfoReply> createGetTableEntryLookupInfoReply(GetTableEntryLookupInfoReply value) {
        return new JAXBElement<GetTableEntryLookupInfoReply>(_GetTableEntryLookupInfoReply_QNAME, GetTableEntryLookupInfoReply.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateTableEntryReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "UpdateTableEntryReply")
    public JAXBElement<UpdateTableEntryReply> createUpdateTableEntryReply(UpdateTableEntryReply value) {
        return new JAXBElement<UpdateTableEntryReply>(_UpdateTableEntryReply_QNAME, UpdateTableEntryReply.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTableEntryIDReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "GetTableEntryIDReply")
    public JAXBElement<GetTableEntryIDReply> createGetTableEntryIDReply(GetTableEntryIDReply value) {
        return new JAXBElement<GetTableEntryIDReply>(_GetTableEntryIDReply_QNAME, GetTableEntryIDReply.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddTableEntryRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "AddTableEntryRequest")
    public JAXBElement<AddTableEntryRequest> createAddTableEntryRequest(AddTableEntryRequest value) {
        return new JAXBElement<AddTableEntryRequest>(_AddTableEntryRequest_QNAME, AddTableEntryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTableEntryIDRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "GetTableEntryIDRequest")
    public JAXBElement<GetTableEntryIDRequest> createGetTableEntryIDRequest(GetTableEntryIDRequest value) {
        return new JAXBElement<GetTableEntryIDRequest>(_GetTableEntryIDRequest_QNAME, GetTableEntryIDRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTableEntryListRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "GetTableEntryListRequest")
    public JAXBElement<GetTableEntryListRequest> createGetTableEntryListRequest(GetTableEntryListRequest value) {
        return new JAXBElement<GetTableEntryListRequest>(_GetTableEntryListRequest_QNAME, GetTableEntryListRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteTableEntryRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "DeleteTableEntryRequest")
    public JAXBElement<DeleteTableEntryRequest> createDeleteTableEntryRequest(DeleteTableEntryRequest value) {
        return new JAXBElement<DeleteTableEntryRequest>(_DeleteTableEntryRequest_QNAME, DeleteTableEntryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTableEntryDataReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "GetTableEntryDataReply")
    public JAXBElement<GetTableEntryDataReply> createGetTableEntryDataReply(GetTableEntryDataReply value) {
        return new JAXBElement<GetTableEntryDataReply>(_GetTableEntryDataReply_QNAME, GetTableEntryDataReply.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteTableEntryReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "DeleteTableEntryReply")
    public JAXBElement<DeleteTableEntryReply> createDeleteTableEntryReply(DeleteTableEntryReply value) {
        return new JAXBElement<DeleteTableEntryReply>(_DeleteTableEntryReply_QNAME, DeleteTableEntryReply.class, null, value);
    }

}
