//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 12:58:05 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "blackbaud_appfx_server_bizops", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package EventExpenseType;
