//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 12:58:05 PM EST 
//


package EventExpenseType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpdateTableEntryRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateTableEntryRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{blackbaud_appfx_server_bizops}BizOpsRequest">
 *       &lt;sequence>
 *         &lt;element name="TableEntryDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TableEntryID" type="{http://microsoft.com/wsdl/types/}guid"/>
 *         &lt;element name="Inactive" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateTableEntryRequest", propOrder = {
    "tableEntryDescription",
    "tableEntryID",
    "inactive",
    "sequence"
})
public class UpdateTableEntryRequest
    extends BizOpsRequest
{

    @XmlElement(name = "TableEntryDescription")
    protected String tableEntryDescription;
    @XmlElement(name = "TableEntryID", required = true)
    protected String tableEntryID;
    @XmlElement(name = "Inactive")
    protected boolean inactive;
    @XmlElement(name = "Sequence")
    protected int sequence;

    /**
     * Gets the value of the tableEntryDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableEntryDescription() {
        return tableEntryDescription;
    }

    /**
     * Sets the value of the tableEntryDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableEntryDescription(String value) {
        this.tableEntryDescription = value;
    }

    /**
     * Gets the value of the tableEntryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableEntryID() {
        return tableEntryID;
    }

    /**
     * Sets the value of the tableEntryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableEntryID(String value) {
        this.tableEntryID = value;
    }

    /**
     * Gets the value of the inactive property.
     * 
     */
    public boolean isInactive() {
        return inactive;
    }

    /**
     * Sets the value of the inactive property.
     * 
     */
    public void setInactive(boolean value) {
        this.inactive = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     */
    public int getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     */
    public void setSequence(int value) {
        this.sequence = value;
    }

}
