//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 11:16:38 AM EST 
//


package AltruEventCalendarItemListListService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FilterData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilterData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="STARTDATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ENDDATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="EVENTLOCATIONID" type="{http://microsoft.com/wsdl/types/}guid"/>
 *         &lt;element name="ONLYSHOWUSERSEVENTS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="INCLUDEINVITATIONS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilterData", propOrder = {
    "startdate",
    "enddate",
    "eventlocationid",
    "onlyshowusersevents",
    "includeinvitations"
})
public class FilterData {

    @XmlElement(name = "STARTDATE", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startdate;
    @XmlElement(name = "ENDDATE", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar enddate;
    @XmlElement(name = "EVENTLOCATIONID", required = true, nillable = true)
    protected String eventlocationid;
    @XmlElement(name = "ONLYSHOWUSERSEVENTS", required = true, type = Boolean.class, nillable = true)
    protected Boolean onlyshowusersevents;
    @XmlElement(name = "INCLUDEINVITATIONS", required = true, type = Boolean.class, nillable = true)
    protected Boolean includeinvitations;

    /**
     * Gets the value of the startdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSTARTDATE() {
        return startdate;
    }

    /**
     * Sets the value of the startdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSTARTDATE(XMLGregorianCalendar value) {
        this.startdate = value;
    }

    /**
     * Gets the value of the enddate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getENDDATE() {
        return enddate;
    }

    /**
     * Sets the value of the enddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setENDDATE(XMLGregorianCalendar value) {
        this.enddate = value;
    }

    /**
     * Gets the value of the eventlocationid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEVENTLOCATIONID() {
        return eventlocationid;
    }

    /**
     * Sets the value of the eventlocationid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEVENTLOCATIONID(String value) {
        this.eventlocationid = value;
    }

    /**
     * Gets the value of the onlyshowusersevents property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isONLYSHOWUSERSEVENTS() {
        return onlyshowusersevents;
    }

    /**
     * Sets the value of the onlyshowusersevents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setONLYSHOWUSERSEVENTS(Boolean value) {
        this.onlyshowusersevents = value;
    }

    /**
     * Gets the value of the includeinvitations property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isINCLUDEINVITATIONS() {
        return includeinvitations;
    }

    /**
     * Sets the value of the includeinvitations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setINCLUDEINVITATIONS(Boolean value) {
        this.includeinvitations = value;
    }

}
