//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 11:16:38 AM EST 
//


package AltruEventCalendarItemListListService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetRowsRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetRowsRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{blackbaud_appfx_server_bizops}BizOpsRequest">
 *       &lt;sequence>
 *         &lt;element name="MaxRows" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="SecurityContext" type="{blackbaud_appfx_server_bizops}BizOpsRequestSecurityContext" minOccurs="0"/>
 *         &lt;element name="Filter" type="{blackbaud_appfx_server_bizops}FilterData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetRowsRequest", propOrder = {
    "maxRows",
    "securityContext",
    "filter"
})
public class GetRowsRequest
    extends BizOpsRequest
{

    @XmlElement(name = "MaxRows", defaultValue = "0")
    protected Integer maxRows;
    @XmlElement(name = "SecurityContext")
    protected BizOpsRequestSecurityContext securityContext;
    @XmlElement(name = "Filter")
    protected FilterData filter;

    /**
     * Gets the value of the maxRows property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxRows() {
        return maxRows;
    }

    /**
     * Sets the value of the maxRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxRows(Integer value) {
        this.maxRows = value;
    }

    /**
     * Gets the value of the securityContext property.
     * 
     * @return
     *     possible object is
     *     {@link BizOpsRequestSecurityContext }
     *     
     */
    public BizOpsRequestSecurityContext getSecurityContext() {
        return securityContext;
    }

    /**
     * Sets the value of the securityContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link BizOpsRequestSecurityContext }
     *     
     */
    public void setSecurityContext(BizOpsRequestSecurityContext value) {
        this.securityContext = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link FilterData }
     *     
     */
    public FilterData getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterData }
     *     
     */
    public void setFilter(FilterData value) {
        this.filter = value;
    }

}
