//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 11:16:38 AM EST 
//


package AltruEventCalendarItemListListService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pingMessageIn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pingMessageIn"
})
@XmlRootElement(name = "PingRequest")
public class PingRequest {

    protected String pingMessageIn;

    /**
     * Gets the value of the pingMessageIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPingMessageIn() {
        return pingMessageIn;
    }

    /**
     * Sets the value of the pingMessageIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPingMessageIn(String value) {
        this.pingMessageIn = value;
    }

}
