//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 11:16:43 AM EST 
//


package EventExpenseEditRecordOperation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoadDataReply complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoadDataReply">
 *   &lt;complexContent>
 *     &lt;extension base="{blackbaud_appfx_server_bizops}BizOpsReply">
 *       &lt;sequence>
 *         &lt;element name="RecordData" type="{blackbaud_appfx_server_bizops}RecordData" minOccurs="0"/>
 *         &lt;element name="TSLong" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoadDataReply", propOrder = {
    "recordData",
    "tsLong"
})
@XmlRootElement(name = "LoadDataReply")
public class LoadDataReply
    extends BizOpsReply
{

    @XmlElement(name = "RecordData")
    protected RecordData recordData;
    @XmlElement(name = "TSLong")
    protected long tsLong;

    /**
     * Gets the value of the recordData property.
     * 
     * @return
     *     possible object is
     *     {@link RecordData }
     *     
     */
    public RecordData getRecordData() {
        return recordData;
    }

    /**
     * Sets the value of the recordData property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordData }
     *     
     */
    public void setRecordData(RecordData value) {
        this.recordData = value;
    }

    /**
     * Gets the value of the tsLong property.
     * 
     */
    public long getTSLong() {
        return tsLong;
    }

    /**
     * Sets the value of the tsLong property.
     * 
     */
    public void setTSLong(long value) {
        this.tsLong = value;
    }

}
