//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 11:16:43 AM EST 
//


package EventExpenseEditRecordOperation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the EventExpenseEditRecordOperation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SaveDataReply_QNAME = new QName("blackbaud_appfx_server_bizops", "SaveDataReply");
    private final static QName _LoadDataRequest_QNAME = new QName("blackbaud_appfx_server_bizops", "LoadDataRequest");
    private final static QName _SaveDataRequest_QNAME = new QName("blackbaud_appfx_server_bizops", "SaveDataRequest");
    private final static QName _LoadDataReply_QNAME = new QName("blackbaud_appfx_server_bizops", "LoadDataReply");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: EventExpenseEditRecordOperation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PingReply }
     * 
     */
    public PingReply createPingReply() {
        return new PingReply();
    }

    /**
     * Create an instance of {@link SaveDataRequest }
     * 
     */
    public SaveDataRequest createSaveDataRequest() {
        return new SaveDataRequest();
    }

    /**
     * Create an instance of {@link BizOpsErrorDetail }
     * 
     */
    public BizOpsErrorDetail createBizOpsErrorDetail() {
        return new BizOpsErrorDetail();
    }

    /**
     * Create an instance of {@link LoadDataRequest }
     * 
     */
    public LoadDataRequest createLoadDataRequest() {
        return new LoadDataRequest();
    }

    /**
     * Create an instance of {@link SessionStartReply }
     * 
     */
    public SessionStartReply createSessionStartReply() {
        return new SessionStartReply();
    }

    /**
     * Create an instance of {@link SessionEndRequest }
     * 
     */
    public SessionEndRequest createSessionEndRequest() {
        return new SessionEndRequest();
    }

    /**
     * Create an instance of {@link BizOpsSessionStartReply }
     * 
     */
    public BizOpsSessionStartReply createBizOpsSessionStartReply() {
        return new BizOpsSessionStartReply();
    }

    /**
     * Create an instance of {@link LoadDataReply }
     * 
     */
    public LoadDataReply createLoadDataReply() {
        return new LoadDataReply();
    }

    /**
     * Create an instance of {@link SaveDataReply }
     * 
     */
    public SaveDataReply createSaveDataReply() {
        return new SaveDataReply();
    }

    /**
     * Create an instance of {@link PingRequest }
     * 
     */
    public PingRequest createPingRequest() {
        return new PingRequest();
    }

    /**
     * Create an instance of {@link BizOpsRequestSecurityContext }
     * 
     */
    public BizOpsRequestSecurityContext createBizOpsRequestSecurityContext() {
        return new BizOpsRequestSecurityContext();
    }

    /**
     * Create an instance of {@link RecordData }
     * 
     */
    public RecordData createRecordData() {
        return new RecordData();
    }

    /**
     * Create an instance of {@link SessionStartRequest }
     * 
     */
    public SessionStartRequest createSessionStartRequest() {
        return new SessionStartRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SaveDataReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "SaveDataReply")
    public JAXBElement<SaveDataReply> createSaveDataReply(SaveDataReply value) {
        return new JAXBElement<SaveDataReply>(_SaveDataReply_QNAME, SaveDataReply.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadDataRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "LoadDataRequest")
    public JAXBElement<LoadDataRequest> createLoadDataRequest(LoadDataRequest value) {
        return new JAXBElement<LoadDataRequest>(_LoadDataRequest_QNAME, LoadDataRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SaveDataRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "SaveDataRequest")
    public JAXBElement<SaveDataRequest> createSaveDataRequest(SaveDataRequest value) {
        return new JAXBElement<SaveDataRequest>(_SaveDataRequest_QNAME, SaveDataRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadDataReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "LoadDataReply")
    public JAXBElement<LoadDataReply> createLoadDataReply(LoadDataReply value) {
        return new JAXBElement<LoadDataReply>(_LoadDataReply_QNAME, LoadDataReply.class, null, value);
    }

}
