//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 11:16:43 AM EST 
//


package EventExpenseEditRecordOperation;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RecordData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecordData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EVENTEXPENSETYPECODEID" type="{http://microsoft.com/wsdl/types/}guid"/>
 *         &lt;element name="EVENTEXPENSETYPECODEID_VALUETRANSLATION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VENDORID" type="{http://microsoft.com/wsdl/types/}guid"/>
 *         &lt;element name="BUDGETEDAMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ACTUALAMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="AMOUNTPAID" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="DATEDUE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DATEPAID" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="COMMENT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BASECURRENCYID" type="{http://microsoft.com/wsdl/types/}guid"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecordData", propOrder = {
    "eventexpensetypecodeid",
    "eventexpensetypecodeidvaluetranslation",
    "vendorid",
    "budgetedamount",
    "actualamount",
    "amountpaid",
    "datedue",
    "datepaid",
    "comment",
    "basecurrencyid"
})
public class RecordData {

    @XmlElement(name = "EVENTEXPENSETYPECODEID", required = true, nillable = true)
    protected String eventexpensetypecodeid;
    @XmlElement(name = "EVENTEXPENSETYPECODEID_VALUETRANSLATION")
    protected String eventexpensetypecodeidvaluetranslation;
    @XmlElement(name = "VENDORID", required = true, nillable = true)
    protected String vendorid;
    @XmlElement(name = "BUDGETEDAMOUNT", required = true, nillable = true)
    protected BigDecimal budgetedamount;
    @XmlElement(name = "ACTUALAMOUNT", required = true, nillable = true)
    protected BigDecimal actualamount;
    @XmlElement(name = "AMOUNTPAID", required = true, nillable = true)
    protected BigDecimal amountpaid;
    @XmlElement(name = "DATEDUE", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datedue;
    @XmlElement(name = "DATEPAID", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datepaid;
    @XmlElement(name = "COMMENT")
    protected String comment;
    @XmlElement(name = "BASECURRENCYID", required = true, nillable = true)
    protected String basecurrencyid;

    /**
     * Gets the value of the eventexpensetypecodeid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEVENTEXPENSETYPECODEID() {
        return eventexpensetypecodeid;
    }

    /**
     * Sets the value of the eventexpensetypecodeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEVENTEXPENSETYPECODEID(String value) {
        this.eventexpensetypecodeid = value;
    }

    /**
     * Gets the value of the eventexpensetypecodeidvaluetranslation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEVENTEXPENSETYPECODEIDVALUETRANSLATION() {
        return eventexpensetypecodeidvaluetranslation;
    }

    /**
     * Sets the value of the eventexpensetypecodeidvaluetranslation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEVENTEXPENSETYPECODEIDVALUETRANSLATION(String value) {
        this.eventexpensetypecodeidvaluetranslation = value;
    }

    /**
     * Gets the value of the vendorid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVENDORID() {
        return vendorid;
    }

    /**
     * Sets the value of the vendorid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVENDORID(String value) {
        this.vendorid = value;
    }

    /**
     * Gets the value of the budgetedamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBUDGETEDAMOUNT() {
        return budgetedamount;
    }

    /**
     * Sets the value of the budgetedamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBUDGETEDAMOUNT(BigDecimal value) {
        this.budgetedamount = value;
    }

    /**
     * Gets the value of the actualamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getACTUALAMOUNT() {
        return actualamount;
    }

    /**
     * Sets the value of the actualamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setACTUALAMOUNT(BigDecimal value) {
        this.actualamount = value;
    }

    /**
     * Gets the value of the amountpaid property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAMOUNTPAID() {
        return amountpaid;
    }

    /**
     * Sets the value of the amountpaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAMOUNTPAID(BigDecimal value) {
        this.amountpaid = value;
    }

    /**
     * Gets the value of the datedue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATEDUE() {
        return datedue;
    }

    /**
     * Sets the value of the datedue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATEDUE(XMLGregorianCalendar value) {
        this.datedue = value;
    }

    /**
     * Gets the value of the datepaid property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATEPAID() {
        return datepaid;
    }

    /**
     * Sets the value of the datepaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATEPAID(XMLGregorianCalendar value) {
        this.datepaid = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMENT() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMENT(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the basecurrencyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBASECURRENCYID() {
        return basecurrencyid;
    }

    /**
     * Sets the value of the basecurrencyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBASECURRENCYID(String value) {
        this.basecurrencyid = value;
    }

}
