//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 11:16:37 AM EST 
//


package blackbaud_appfx_ws_getdblist;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the blackbaud_appfx_ws_getdblist package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: blackbaud_appfx_ws_getdblist
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPwdHelpUrlRequest }
     * 
     */
    public GetPwdHelpUrlRequest createGetPwdHelpUrlRequest() {
        return new GetPwdHelpUrlRequest();
    }

    /**
     * Create an instance of {@link GetDBListStringRequest }
     * 
     */
    public GetDBListStringRequest createGetDBListStringRequest() {
        return new GetDBListStringRequest();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link GetPwdHelpReply }
     * 
     */
    public GetPwdHelpReply createGetPwdHelpReply() {
        return new GetPwdHelpReply();
    }

    /**
     * Create an instance of {@link GetDBListForSiteRequest }
     * 
     */
    public GetDBListForSiteRequest createGetDBListForSiteRequest() {
        return new GetDBListForSiteRequest();
    }

    /**
     * Create an instance of {@link GetDBListRequest }
     * 
     */
    public GetDBListRequest createGetDBListRequest() {
        return new GetDBListRequest();
    }

    /**
     * Create an instance of {@link GetDBListForSiteReply }
     * 
     */
    public GetDBListForSiteReply createGetDBListForSiteReply() {
        return new GetDBListForSiteReply();
    }

    /**
     * Create an instance of {@link GetDBListStringReply }
     * 
     */
    public GetDBListStringReply createGetDBListStringReply() {
        return new GetDBListStringReply();
    }

    /**
     * Create an instance of {@link GetDBListReply }
     * 
     */
    public GetDBListReply createGetDBListReply() {
        return new GetDBListReply();
    }

}
