//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 11:16:42 AM EST 
//


package EventExpenseDeleteRecordOperation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the EventExpenseDeleteRecordOperation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExecuteRecordOperationReply_QNAME = new QName("blackbaud_appfx_server_bizops", "ExecuteRecordOperationReply");
    private final static QName _GetPromptReply_QNAME = new QName("blackbaud_appfx_server_bizops", "GetPromptReply");
    private final static QName _ExecuteRecordOperationRequest_QNAME = new QName("blackbaud_appfx_server_bizops", "ExecuteRecordOperationRequest");
    private final static QName _GetPromptRequest_QNAME = new QName("blackbaud_appfx_server_bizops", "GetPromptRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: EventExpenseDeleteRecordOperation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SessionEndRequest }
     * 
     */
    public SessionEndRequest createSessionEndRequest() {
        return new SessionEndRequest();
    }

    /**
     * Create an instance of {@link GetPromptRequest }
     * 
     */
    public GetPromptRequest createGetPromptRequest() {
        return new GetPromptRequest();
    }

    /**
     * Create an instance of {@link GetPromptReply }
     * 
     */
    public GetPromptReply createGetPromptReply() {
        return new GetPromptReply();
    }

    /**
     * Create an instance of {@link SessionStartReply }
     * 
     */
    public SessionStartReply createSessionStartReply() {
        return new SessionStartReply();
    }

    /**
     * Create an instance of {@link SessionStartRequest }
     * 
     */
    public SessionStartRequest createSessionStartRequest() {
        return new SessionStartRequest();
    }

    /**
     * Create an instance of {@link BizOpsErrorDetail }
     * 
     */
    public BizOpsErrorDetail createBizOpsErrorDetail() {
        return new BizOpsErrorDetail();
    }

    /**
     * Create an instance of {@link ExecuteRecordOperationRequest }
     * 
     */
    public ExecuteRecordOperationRequest createExecuteRecordOperationRequest() {
        return new ExecuteRecordOperationRequest();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link PingReply }
     * 
     */
    public PingReply createPingReply() {
        return new PingReply();
    }

    /**
     * Create an instance of {@link BizOpsRequestSecurityContext }
     * 
     */
    public BizOpsRequestSecurityContext createBizOpsRequestSecurityContext() {
        return new BizOpsRequestSecurityContext();
    }

    /**
     * Create an instance of {@link ExecuteRecordOperationReply }
     * 
     */
    public ExecuteRecordOperationReply createExecuteRecordOperationReply() {
        return new ExecuteRecordOperationReply();
    }

    /**
     * Create an instance of {@link PingRequest }
     * 
     */
    public PingRequest createPingRequest() {
        return new PingRequest();
    }

    /**
     * Create an instance of {@link BizOpsSessionStartReply }
     * 
     */
    public BizOpsSessionStartReply createBizOpsSessionStartReply() {
        return new BizOpsSessionStartReply();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExecuteRecordOperationReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "ExecuteRecordOperationReply")
    public JAXBElement<ExecuteRecordOperationReply> createExecuteRecordOperationReply(ExecuteRecordOperationReply value) {
        return new JAXBElement<ExecuteRecordOperationReply>(_ExecuteRecordOperationReply_QNAME, ExecuteRecordOperationReply.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPromptReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "GetPromptReply")
    public JAXBElement<GetPromptReply> createGetPromptReply(GetPromptReply value) {
        return new JAXBElement<GetPromptReply>(_GetPromptReply_QNAME, GetPromptReply.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExecuteRecordOperationRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "ExecuteRecordOperationRequest")
    public JAXBElement<ExecuteRecordOperationRequest> createExecuteRecordOperationRequest(ExecuteRecordOperationRequest value) {
        return new JAXBElement<ExecuteRecordOperationRequest>(_ExecuteRecordOperationRequest_QNAME, ExecuteRecordOperationRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPromptRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "GetPromptRequest")
    public JAXBElement<GetPromptRequest> createGetPromptRequest(GetPromptRequest value) {
        return new JAXBElement<GetPromptRequest>(_GetPromptRequest_QNAME, GetPromptRequest.class, null, value);
    }

}
