//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 11:16:40 AM EST 
//


package EventCalendarEventListService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BizOpsErrorDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BizOpsErrorDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServiceErrorCode" type="{blackbaud_appfx_server_bizops}ServiceErrorCode"/>
 *         &lt;element name="ServiceErrorCodeNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ErrorName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ErrorText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ErrorDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DataFormErrorCode" type="{blackbaud_appfx_server_bizops}DataFormErrorCode"/>
 *         &lt;element name="DataFormErrorCodeNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DataFormErrorInvalidFieldID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DataFormErrorInvalidFieldReason" type="{blackbaud_appfx_server_bizops}DataFormInvalidFieldReason"/>
 *         &lt;element name="DataFormErrorInvalidFieldCollectionFieldID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SQLErrorNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="SQLErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SQLErrorSeverity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="SQLErrorState" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="SQLErrorProcedure" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SQLErrorLineNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="SQLErrorIsConcurrency" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BizOpsErrorDetail", propOrder = {
    "serviceErrorCode",
    "serviceErrorCodeNumber",
    "errorName",
    "errorText",
    "errorDetails",
    "dataFormErrorCode",
    "dataFormErrorCodeNumber",
    "dataFormErrorInvalidFieldID",
    "dataFormErrorInvalidFieldReason",
    "dataFormErrorInvalidFieldCollectionFieldID",
    "sqlErrorNumber",
    "sqlErrorMessage",
    "sqlErrorSeverity",
    "sqlErrorState",
    "sqlErrorProcedure",
    "sqlErrorLineNumber",
    "sqlErrorIsConcurrency"
})
public class BizOpsErrorDetail {

    @XmlElement(name = "ServiceErrorCode", required = true)
    protected ServiceErrorCode serviceErrorCode;
    @XmlElement(name = "ServiceErrorCodeNumber")
    protected int serviceErrorCodeNumber;
    @XmlElement(name = "ErrorName")
    protected String errorName;
    @XmlElement(name = "ErrorText")
    protected String errorText;
    @XmlElement(name = "ErrorDetails")
    protected String errorDetails;
    @XmlElement(name = "DataFormErrorCode", required = true)
    protected DataFormErrorCode dataFormErrorCode;
    @XmlElement(name = "DataFormErrorCodeNumber")
    protected int dataFormErrorCodeNumber;
    @XmlElement(name = "DataFormErrorInvalidFieldID")
    protected String dataFormErrorInvalidFieldID;
    @XmlElement(name = "DataFormErrorInvalidFieldReason", required = true, nillable = true)
    protected DataFormInvalidFieldReason dataFormErrorInvalidFieldReason;
    @XmlElement(name = "DataFormErrorInvalidFieldCollectionFieldID")
    protected String dataFormErrorInvalidFieldCollectionFieldID;
    @XmlElement(name = "SQLErrorNumber", defaultValue = "0")
    protected Integer sqlErrorNumber;
    @XmlElement(name = "SQLErrorMessage")
    protected String sqlErrorMessage;
    @XmlElement(name = "SQLErrorSeverity", defaultValue = "0")
    protected Integer sqlErrorSeverity;
    @XmlElement(name = "SQLErrorState", defaultValue = "0")
    protected Integer sqlErrorState;
    @XmlElement(name = "SQLErrorProcedure")
    protected String sqlErrorProcedure;
    @XmlElement(name = "SQLErrorLineNumber", defaultValue = "0")
    protected Integer sqlErrorLineNumber;
    @XmlElement(name = "SQLErrorIsConcurrency", defaultValue = "false")
    protected Boolean sqlErrorIsConcurrency;

    /**
     * Gets the value of the serviceErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceErrorCode }
     *     
     */
    public ServiceErrorCode getServiceErrorCode() {
        return serviceErrorCode;
    }

    /**
     * Sets the value of the serviceErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceErrorCode }
     *     
     */
    public void setServiceErrorCode(ServiceErrorCode value) {
        this.serviceErrorCode = value;
    }

    /**
     * Gets the value of the serviceErrorCodeNumber property.
     * 
     */
    public int getServiceErrorCodeNumber() {
        return serviceErrorCodeNumber;
    }

    /**
     * Sets the value of the serviceErrorCodeNumber property.
     * 
     */
    public void setServiceErrorCodeNumber(int value) {
        this.serviceErrorCodeNumber = value;
    }

    /**
     * Gets the value of the errorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorName() {
        return errorName;
    }

    /**
     * Sets the value of the errorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorName(String value) {
        this.errorName = value;
    }

    /**
     * Gets the value of the errorText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorText() {
        return errorText;
    }

    /**
     * Sets the value of the errorText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorText(String value) {
        this.errorText = value;
    }

    /**
     * Gets the value of the errorDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorDetails() {
        return errorDetails;
    }

    /**
     * Sets the value of the errorDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorDetails(String value) {
        this.errorDetails = value;
    }

    /**
     * Gets the value of the dataFormErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link DataFormErrorCode }
     *     
     */
    public DataFormErrorCode getDataFormErrorCode() {
        return dataFormErrorCode;
    }

    /**
     * Sets the value of the dataFormErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataFormErrorCode }
     *     
     */
    public void setDataFormErrorCode(DataFormErrorCode value) {
        this.dataFormErrorCode = value;
    }

    /**
     * Gets the value of the dataFormErrorCodeNumber property.
     * 
     */
    public int getDataFormErrorCodeNumber() {
        return dataFormErrorCodeNumber;
    }

    /**
     * Sets the value of the dataFormErrorCodeNumber property.
     * 
     */
    public void setDataFormErrorCodeNumber(int value) {
        this.dataFormErrorCodeNumber = value;
    }

    /**
     * Gets the value of the dataFormErrorInvalidFieldID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFormErrorInvalidFieldID() {
        return dataFormErrorInvalidFieldID;
    }

    /**
     * Sets the value of the dataFormErrorInvalidFieldID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFormErrorInvalidFieldID(String value) {
        this.dataFormErrorInvalidFieldID = value;
    }

    /**
     * Gets the value of the dataFormErrorInvalidFieldReason property.
     * 
     * @return
     *     possible object is
     *     {@link DataFormInvalidFieldReason }
     *     
     */
    public DataFormInvalidFieldReason getDataFormErrorInvalidFieldReason() {
        return dataFormErrorInvalidFieldReason;
    }

    /**
     * Sets the value of the dataFormErrorInvalidFieldReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataFormInvalidFieldReason }
     *     
     */
    public void setDataFormErrorInvalidFieldReason(DataFormInvalidFieldReason value) {
        this.dataFormErrorInvalidFieldReason = value;
    }

    /**
     * Gets the value of the dataFormErrorInvalidFieldCollectionFieldID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFormErrorInvalidFieldCollectionFieldID() {
        return dataFormErrorInvalidFieldCollectionFieldID;
    }

    /**
     * Sets the value of the dataFormErrorInvalidFieldCollectionFieldID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFormErrorInvalidFieldCollectionFieldID(String value) {
        this.dataFormErrorInvalidFieldCollectionFieldID = value;
    }

    /**
     * Gets the value of the sqlErrorNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSQLErrorNumber() {
        return sqlErrorNumber;
    }

    /**
     * Sets the value of the sqlErrorNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSQLErrorNumber(Integer value) {
        this.sqlErrorNumber = value;
    }

    /**
     * Gets the value of the sqlErrorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSQLErrorMessage() {
        return sqlErrorMessage;
    }

    /**
     * Sets the value of the sqlErrorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSQLErrorMessage(String value) {
        this.sqlErrorMessage = value;
    }

    /**
     * Gets the value of the sqlErrorSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSQLErrorSeverity() {
        return sqlErrorSeverity;
    }

    /**
     * Sets the value of the sqlErrorSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSQLErrorSeverity(Integer value) {
        this.sqlErrorSeverity = value;
    }

    /**
     * Gets the value of the sqlErrorState property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSQLErrorState() {
        return sqlErrorState;
    }

    /**
     * Sets the value of the sqlErrorState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSQLErrorState(Integer value) {
        this.sqlErrorState = value;
    }

    /**
     * Gets the value of the sqlErrorProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSQLErrorProcedure() {
        return sqlErrorProcedure;
    }

    /**
     * Sets the value of the sqlErrorProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSQLErrorProcedure(String value) {
        this.sqlErrorProcedure = value;
    }

    /**
     * Gets the value of the sqlErrorLineNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSQLErrorLineNumber() {
        return sqlErrorLineNumber;
    }

    /**
     * Sets the value of the sqlErrorLineNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSQLErrorLineNumber(Integer value) {
        this.sqlErrorLineNumber = value;
    }

    /**
     * Gets the value of the sqlErrorIsConcurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSQLErrorIsConcurrency() {
        return sqlErrorIsConcurrency;
    }

    /**
     * Sets the value of the sqlErrorIsConcurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSQLErrorIsConcurrency(Boolean value) {
        this.sqlErrorIsConcurrency = value;
    }

}
