//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 11:16:44 AM EST 
//


package ConstituentSearch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListRow complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListRow">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://microsoft.com/wsdl/types/}guid"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Postcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LookupID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GivesAnonymously" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="IsOrganization" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ConstituentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SortConstituentName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsGroup" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="IsHousehold" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListRow", propOrder = {
    "id",
    "name",
    "address",
    "city",
    "state",
    "postcode",
    "lookupID",
    "givesAnonymously",
    "isOrganization",
    "constituentType",
    "sortConstituentName",
    "isGroup",
    "isHousehold"
})
public class ListRow {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Address")
    protected String address;
    @XmlElement(name = "City")
    protected String city;
    @XmlElement(name = "State")
    protected String state;
    @XmlElement(name = "Postcode")
    protected String postcode;
    @XmlElement(name = "LookupID")
    protected String lookupID;
    @XmlElement(name = "GivesAnonymously")
    protected boolean givesAnonymously;
    @XmlElement(name = "IsOrganization")
    protected boolean isOrganization;
    @XmlElement(name = "ConstituentType")
    protected String constituentType;
    @XmlElement(name = "SortConstituentName")
    protected String sortConstituentName;
    @XmlElement(name = "IsGroup")
    protected boolean isGroup;
    @XmlElement(name = "IsHousehold")
    protected boolean isHousehold;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the postcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * Sets the value of the postcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostcode(String value) {
        this.postcode = value;
    }

    /**
     * Gets the value of the lookupID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLookupID() {
        return lookupID;
    }

    /**
     * Sets the value of the lookupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLookupID(String value) {
        this.lookupID = value;
    }

    /**
     * Gets the value of the givesAnonymously property.
     * 
     */
    public boolean isGivesAnonymously() {
        return givesAnonymously;
    }

    /**
     * Sets the value of the givesAnonymously property.
     * 
     */
    public void setGivesAnonymously(boolean value) {
        this.givesAnonymously = value;
    }

    /**
     * Gets the value of the isOrganization property.
     * 
     */
    public boolean isIsOrganization() {
        return isOrganization;
    }

    /**
     * Sets the value of the isOrganization property.
     * 
     */
    public void setIsOrganization(boolean value) {
        this.isOrganization = value;
    }

    /**
     * Gets the value of the constituentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConstituentType() {
        return constituentType;
    }

    /**
     * Sets the value of the constituentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConstituentType(String value) {
        this.constituentType = value;
    }

    /**
     * Gets the value of the sortConstituentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortConstituentName() {
        return sortConstituentName;
    }

    /**
     * Sets the value of the sortConstituentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortConstituentName(String value) {
        this.sortConstituentName = value;
    }

    /**
     * Gets the value of the isGroup property.
     * 
     */
    public boolean isIsGroup() {
        return isGroup;
    }

    /**
     * Sets the value of the isGroup property.
     * 
     */
    public void setIsGroup(boolean value) {
        this.isGroup = value;
    }

    /**
     * Gets the value of the isHousehold property.
     * 
     */
    public boolean isIsHousehold() {
        return isHousehold;
    }

    /**
     * Sets the value of the isHousehold property.
     * 
     */
    public void setIsHousehold(boolean value) {
        this.isHousehold = value;
    }

}
