//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 11:16:44 AM EST 
//


package ConstituentSearch;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ConstituentSearch package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TranslateIDRequest_QNAME = new QName("blackbaud_appfx_server_bizops", "TranslateIDRequest");
    private final static QName _TranslateIDReply_QNAME = new QName("blackbaud_appfx_server_bizops", "TranslateIDReply");
    private final static QName _SearchReply_QNAME = new QName("blackbaud_appfx_server_bizops", "SearchReply");
    private final static QName _SearchRequest_QNAME = new QName("blackbaud_appfx_server_bizops", "SearchRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ConstituentSearch
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BizOpsErrorDetail }
     * 
     */
    public BizOpsErrorDetail createBizOpsErrorDetail() {
        return new BizOpsErrorDetail();
    }

    /**
     * Create an instance of {@link TranslateIDEzRequest }
     * 
     */
    public TranslateIDEzRequest createTranslateIDEzRequest() {
        return new TranslateIDEzRequest();
    }

    /**
     * Create an instance of {@link PingReply }
     * 
     */
    public PingReply createPingReply() {
        return new PingReply();
    }

    /**
     * Create an instance of {@link SearchReply }
     * 
     */
    public SearchReply createSearchReply() {
        return new SearchReply();
    }

    /**
     * Create an instance of {@link ListRow }
     * 
     */
    public ListRow createListRow() {
        return new ListRow();
    }

    /**
     * Create an instance of {@link SearchCriteria }
     * 
     */
    public SearchCriteria createSearchCriteria() {
        return new SearchCriteria();
    }

    /**
     * Create an instance of {@link TranslateIDEzReply }
     * 
     */
    public TranslateIDEzReply createTranslateIDEzReply() {
        return new TranslateIDEzReply();
    }

    /**
     * Create an instance of {@link SessionStartRequest }
     * 
     */
    public SessionStartRequest createSessionStartRequest() {
        return new SessionStartRequest();
    }

    /**
     * Create an instance of {@link TranslateIDReply }
     * 
     */
    public TranslateIDReply createTranslateIDReply() {
        return new TranslateIDReply();
    }

    /**
     * Create an instance of {@link SearchRequest }
     * 
     */
    public SearchRequest createSearchRequest() {
        return new SearchRequest();
    }

    /**
     * Create an instance of {@link TranslateIDRequest }
     * 
     */
    public TranslateIDRequest createTranslateIDRequest() {
        return new TranslateIDRequest();
    }

    /**
     * Create an instance of {@link BizOpsSessionStartReply }
     * 
     */
    public BizOpsSessionStartReply createBizOpsSessionStartReply() {
        return new BizOpsSessionStartReply();
    }

    /**
     * Create an instance of {@link SessionStartReply }
     * 
     */
    public SessionStartReply createSessionStartReply() {
        return new SessionStartReply();
    }

    /**
     * Create an instance of {@link SessionEndRequest }
     * 
     */
    public SessionEndRequest createSessionEndRequest() {
        return new SessionEndRequest();
    }

    /**
     * Create an instance of {@link PingRequest }
     * 
     */
    public PingRequest createPingRequest() {
        return new PingRequest();
    }

    /**
     * Create an instance of {@link ArrayOfListRow }
     * 
     */
    public ArrayOfListRow createArrayOfListRow() {
        return new ArrayOfListRow();
    }

    /**
     * Create an instance of {@link BizOpsRequestSecurityContext }
     * 
     */
    public BizOpsRequestSecurityContext createBizOpsRequestSecurityContext() {
        return new BizOpsRequestSecurityContext();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TranslateIDRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "TranslateIDRequest")
    public JAXBElement<TranslateIDRequest> createTranslateIDRequest(TranslateIDRequest value) {
        return new JAXBElement<TranslateIDRequest>(_TranslateIDRequest_QNAME, TranslateIDRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TranslateIDReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "TranslateIDReply")
    public JAXBElement<TranslateIDReply> createTranslateIDReply(TranslateIDReply value) {
        return new JAXBElement<TranslateIDReply>(_TranslateIDReply_QNAME, TranslateIDReply.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "SearchReply")
    public JAXBElement<SearchReply> createSearchReply(SearchReply value) {
        return new JAXBElement<SearchReply>(_SearchReply_QNAME, SearchReply.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "blackbaud_appfx_server_bizops", name = "SearchRequest")
    public JAXBElement<SearchRequest> createSearchRequest(SearchRequest value) {
        return new JAXBElement<SearchRequest>(_SearchRequest_QNAME, SearchRequest.class, null, value);
    }

}
