//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 11:16:44 AM EST 
//


package ConstituentSearch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SearchCriteria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchCriteria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CONSTITUENTTYPE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FULLNAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KEYNAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FIRSTNAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LOOKUPID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ADDRESSBLOCK" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CITY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STATEID" type="{http://microsoft.com/wsdl/types/}guid"/>
 *         &lt;element name="POSTCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INCLUDEINACTIVE" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="INCLUDEDECEASED" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ONLYPRIMARYADDRESS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="EXACTMATCHONLY" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="SSN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CHECKNICKNAME" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CHECKALIASES" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CHECKMERGEDCONSTITUENTS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="MINIMUMDATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="EXCLUDECUSTOMGROUPS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="EXCLUDEHOUSEHOLDS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="INCLUDEINDIVIDUALS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="INCLUDEORGANIZATIONS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="INCLUDEGROUPS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CHECKALTERNATELOOKUPIDS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="FUZZYSEARCHONNAME" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="INCLUDENONCONSTITUENTRECORDS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchCriteria", propOrder = {
    "constituenttype",
    "fullname",
    "keyname",
    "firstname",
    "lookupid",
    "addressblock",
    "city",
    "stateid",
    "postcode",
    "includeinactive",
    "includedeceased",
    "onlyprimaryaddress",
    "exactmatchonly",
    "ssn",
    "checknickname",
    "checkaliases",
    "checkmergedconstituents",
    "minimumdate",
    "excludecustomgroups",
    "excludehouseholds",
    "includeindividuals",
    "includeorganizations",
    "includegroups",
    "checkalternatelookupids",
    "fuzzysearchonname",
    "includenonconstituentrecords"
})
public class SearchCriteria {

    @XmlElement(name = "CONSTITUENTTYPE", required = true, type = Integer.class, nillable = true)
    protected Integer constituenttype;
    @XmlElement(name = "FULLNAME")
    protected String fullname;
    @XmlElement(name = "KEYNAME")
    protected String keyname;
    @XmlElement(name = "FIRSTNAME")
    protected String firstname;
    @XmlElement(name = "LOOKUPID")
    protected String lookupid;
    @XmlElement(name = "ADDRESSBLOCK")
    protected String addressblock;
    @XmlElement(name = "CITY")
    protected String city;
    @XmlElement(name = "STATEID", required = true, nillable = true)
    protected String stateid;
    @XmlElement(name = "POSTCODE")
    protected String postcode;
    @XmlElement(name = "INCLUDEINACTIVE", required = true, type = Boolean.class, nillable = true)
    protected Boolean includeinactive;
    @XmlElement(name = "INCLUDEDECEASED", required = true, type = Boolean.class, nillable = true)
    protected Boolean includedeceased;
    @XmlElement(name = "ONLYPRIMARYADDRESS", required = true, type = Boolean.class, nillable = true)
    protected Boolean onlyprimaryaddress;
    @XmlElement(name = "EXACTMATCHONLY", required = true, type = Boolean.class, nillable = true)
    protected Boolean exactmatchonly;
    @XmlElement(name = "SSN")
    protected String ssn;
    @XmlElement(name = "CHECKNICKNAME", required = true, type = Boolean.class, nillable = true)
    protected Boolean checknickname;
    @XmlElement(name = "CHECKALIASES", required = true, type = Boolean.class, nillable = true)
    protected Boolean checkaliases;
    @XmlElement(name = "CHECKMERGEDCONSTITUENTS", required = true, type = Boolean.class, nillable = true)
    protected Boolean checkmergedconstituents;
    @XmlElement(name = "MINIMUMDATE", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar minimumdate;
    @XmlElement(name = "EXCLUDECUSTOMGROUPS", required = true, type = Boolean.class, nillable = true)
    protected Boolean excludecustomgroups;
    @XmlElement(name = "EXCLUDEHOUSEHOLDS", required = true, type = Boolean.class, nillable = true)
    protected Boolean excludehouseholds;
    @XmlElement(name = "INCLUDEINDIVIDUALS", required = true, type = Boolean.class, nillable = true)
    protected Boolean includeindividuals;
    @XmlElement(name = "INCLUDEORGANIZATIONS", required = true, type = Boolean.class, nillable = true)
    protected Boolean includeorganizations;
    @XmlElement(name = "INCLUDEGROUPS", required = true, type = Boolean.class, nillable = true)
    protected Boolean includegroups;
    @XmlElement(name = "CHECKALTERNATELOOKUPIDS", required = true, type = Boolean.class, nillable = true)
    protected Boolean checkalternatelookupids;
    @XmlElement(name = "FUZZYSEARCHONNAME", required = true, type = Boolean.class, nillable = true)
    protected Boolean fuzzysearchonname;
    @XmlElement(name = "INCLUDENONCONSTITUENTRECORDS", required = true, type = Boolean.class, nillable = true)
    protected Boolean includenonconstituentrecords;

    /**
     * Gets the value of the constituenttype property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCONSTITUENTTYPE() {
        return constituenttype;
    }

    /**
     * Sets the value of the constituenttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCONSTITUENTTYPE(Integer value) {
        this.constituenttype = value;
    }

    /**
     * Gets the value of the fullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFULLNAME() {
        return fullname;
    }

    /**
     * Sets the value of the fullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFULLNAME(String value) {
        this.fullname = value;
    }

    /**
     * Gets the value of the keyname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKEYNAME() {
        return keyname;
    }

    /**
     * Sets the value of the keyname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKEYNAME(String value) {
        this.keyname = value;
    }

    /**
     * Gets the value of the firstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIRSTNAME() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIRSTNAME(String value) {
        this.firstname = value;
    }

    /**
     * Gets the value of the lookupid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOOKUPID() {
        return lookupid;
    }

    /**
     * Sets the value of the lookupid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOOKUPID(String value) {
        this.lookupid = value;
    }

    /**
     * Gets the value of the addressblock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDRESSBLOCK() {
        return addressblock;
    }

    /**
     * Sets the value of the addressblock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDRESSBLOCK(String value) {
        this.addressblock = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCITY() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCITY(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the stateid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATEID() {
        return stateid;
    }

    /**
     * Sets the value of the stateid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATEID(String value) {
        this.stateid = value;
    }

    /**
     * Gets the value of the postcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSTCODE() {
        return postcode;
    }

    /**
     * Sets the value of the postcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSTCODE(String value) {
        this.postcode = value;
    }

    /**
     * Gets the value of the includeinactive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isINCLUDEINACTIVE() {
        return includeinactive;
    }

    /**
     * Sets the value of the includeinactive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setINCLUDEINACTIVE(Boolean value) {
        this.includeinactive = value;
    }

    /**
     * Gets the value of the includedeceased property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isINCLUDEDECEASED() {
        return includedeceased;
    }

    /**
     * Sets the value of the includedeceased property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setINCLUDEDECEASED(Boolean value) {
        this.includedeceased = value;
    }

    /**
     * Gets the value of the onlyprimaryaddress property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isONLYPRIMARYADDRESS() {
        return onlyprimaryaddress;
    }

    /**
     * Sets the value of the onlyprimaryaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setONLYPRIMARYADDRESS(Boolean value) {
        this.onlyprimaryaddress = value;
    }

    /**
     * Gets the value of the exactmatchonly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEXACTMATCHONLY() {
        return exactmatchonly;
    }

    /**
     * Sets the value of the exactmatchonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEXACTMATCHONLY(Boolean value) {
        this.exactmatchonly = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSN() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSN(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the checknickname property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCHECKNICKNAME() {
        return checknickname;
    }

    /**
     * Sets the value of the checknickname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCHECKNICKNAME(Boolean value) {
        this.checknickname = value;
    }

    /**
     * Gets the value of the checkaliases property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCHECKALIASES() {
        return checkaliases;
    }

    /**
     * Sets the value of the checkaliases property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCHECKALIASES(Boolean value) {
        this.checkaliases = value;
    }

    /**
     * Gets the value of the checkmergedconstituents property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCHECKMERGEDCONSTITUENTS() {
        return checkmergedconstituents;
    }

    /**
     * Sets the value of the checkmergedconstituents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCHECKMERGEDCONSTITUENTS(Boolean value) {
        this.checkmergedconstituents = value;
    }

    /**
     * Gets the value of the minimumdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMINIMUMDATE() {
        return minimumdate;
    }

    /**
     * Sets the value of the minimumdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMINIMUMDATE(XMLGregorianCalendar value) {
        this.minimumdate = value;
    }

    /**
     * Gets the value of the excludecustomgroups property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEXCLUDECUSTOMGROUPS() {
        return excludecustomgroups;
    }

    /**
     * Sets the value of the excludecustomgroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEXCLUDECUSTOMGROUPS(Boolean value) {
        this.excludecustomgroups = value;
    }

    /**
     * Gets the value of the excludehouseholds property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEXCLUDEHOUSEHOLDS() {
        return excludehouseholds;
    }

    /**
     * Sets the value of the excludehouseholds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEXCLUDEHOUSEHOLDS(Boolean value) {
        this.excludehouseholds = value;
    }

    /**
     * Gets the value of the includeindividuals property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isINCLUDEINDIVIDUALS() {
        return includeindividuals;
    }

    /**
     * Sets the value of the includeindividuals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setINCLUDEINDIVIDUALS(Boolean value) {
        this.includeindividuals = value;
    }

    /**
     * Gets the value of the includeorganizations property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isINCLUDEORGANIZATIONS() {
        return includeorganizations;
    }

    /**
     * Sets the value of the includeorganizations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setINCLUDEORGANIZATIONS(Boolean value) {
        this.includeorganizations = value;
    }

    /**
     * Gets the value of the includegroups property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isINCLUDEGROUPS() {
        return includegroups;
    }

    /**
     * Sets the value of the includegroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setINCLUDEGROUPS(Boolean value) {
        this.includegroups = value;
    }

    /**
     * Gets the value of the checkalternatelookupids property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCHECKALTERNATELOOKUPIDS() {
        return checkalternatelookupids;
    }

    /**
     * Sets the value of the checkalternatelookupids property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCHECKALTERNATELOOKUPIDS(Boolean value) {
        this.checkalternatelookupids = value;
    }

    /**
     * Gets the value of the fuzzysearchonname property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFUZZYSEARCHONNAME() {
        return fuzzysearchonname;
    }

    /**
     * Sets the value of the fuzzysearchonname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFUZZYSEARCHONNAME(Boolean value) {
        this.fuzzysearchonname = value;
    }

    /**
     * Gets the value of the includenonconstituentrecords property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isINCLUDENONCONSTITUENTRECORDS() {
        return includenonconstituentrecords;
    }

    /**
     * Sets the value of the includenonconstituentrecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setINCLUDENONCONSTITUENTRECORDS(Boolean value) {
        this.includenonconstituentrecords = value;
    }

}
